import { z } from 'zod';

import { createLogger } from '@/lib/logger';

import { backtestDetailSchema, type BacktestDetail, type BacktestSummary } from './types';

/**
 * Reads the demo dataset committed at `mock-data/backtests.json`.
 *
 * The file is generated by `npm run generate:mock-data` (see
 * `tools/generate-mock-data.ts`) and checked in, so a fresh clone renders every
 * chart with no backend running and no build step. This module only loads and
 * validates it — the generation maths lives in `mock-source.ts`, which nothing
 * here imports, so it never reaches the browser bundle.
 */

const log = createLogger('fixtures');

const datasetSchema = z.array(backtestDetailSchema).min(1);

/**
 * Loaded on first use, not at module scope.
 *
 * A static import would pull ~570 KB of JSON into the entry chunk of every
 * build, including production builds that never turn fixtures on. The dynamic
 * import puts it in its own chunk that is only ever fetched when something
 * actually asks for demo data.
 */
let datasetPromise: Promise<BacktestDetail[]> | null = null;

async function dataset(): Promise<BacktestDetail[]> {
  datasetPromise ??= import('@data/backtests.json').then((module) => {
    // Parsed rather than cast: the file is generated, and a generator whose
    // output silently stops matching the schema is exactly the failure this
    // catches — loudly, at load, instead of as `undefined` inside a chart.
    const parsed = datasetSchema.parse(module.default);
    log.info('loaded demo dataset', {
      backtests: parsed.length,
      trades: parsed.reduce((sum, item) => sum + item.trades.length, 0),
    });
    return parsed;
  });

  return datasetPromise;
}

/** The list payload carries no curve or trades, matching the real endpoint. */
function toSummary(detail: BacktestDetail): BacktestSummary {
  const {
    metrics: _metrics,
    equityCurve: _equityCurve,
    trades: _trades,
    parameters: _parameters,
    ...summary
  } = detail;
  return summary;
}

export async function fixtureBacktests(): Promise<BacktestSummary[]> {
  return (await dataset()).map(toSummary);
}

export async function fixtureBacktest(id: string): Promise<BacktestDetail> {
  const found = (await dataset()).find((candidate) => candidate.id === id);
  if (!found) {
    throw new Error(`No backtest with id "${id}" in mock-data/backtests.json`);
  }
  return found;
}
